version: "3.7"

services:
  database:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - database-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: db
    ports:
      - "5432:5432"

volumes:
  database-storage: