-- AlterTable
ALTER TABLE "User" ALTER COLUMN "pos_x" SET DATA TYPE TEXT,
ALTER COLUMN "pos_y" SET DATA TYPE TEXT,
ALTER COLUMN "target_x" SET DATA TYPE TEXT,
ALTER COLUMN "target_y" SET DATA TYPE TEXT;
